name: Backend CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy Node.js Application
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            script: |
                whoami
                cd /root/312TEN034-backend
                npm install pm2 -g
                npx pm2 kill
                git pull origin main
                npm install 
                npm run start:prod
